(function(g){var window=this;var eya=function(a,b,c,d){var e=b.gc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.dc(c,d?d:"mqdefault.jpg");var k=b instanceof g.iQ?g.mX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.eS(f).type;var m=b instanceof g.iQ?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Bn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.gS&&(c.playlist_length=b.getLength());a.update(c)},i7=function(a,b){g.jX.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},j7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",R:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",R:c,K:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.va["ytp-upnext-cancel"];b=this.va["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.U("click",this.UA,this);this.B.Fa(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.M(this,c);c.U("click",this.UA,this);c.Fa(b);this.o=
a;this.J=this.va["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Jt(this.Rm,5E3,this);g.M(this,this.G);this.I=0;this.P(this.va["ytp-upnext-autoplay-icon"],"click",this.QQ);this.RA();this.P(a,"autonavvisibility",this.RA);this.P(a,"mdxnowautoplaying",this.gQ);this.P(a,"mdxautoplaycanceled",this.hQ);this.P(a,"mdxautoplayupnext",this.hD);3==this.o.Ya()&&(a=(a=g.fW(g.aW(this.o)))?a.kI():null)&&this.hD(a)},fya=function(a,b){a.C=b;
eya(a,b,g.X(a.o),"hqdefault.jpg")},k7=function(a,b){a.A||(g.OG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.aH)(),a.A=new g.Jt((0,g.A)(a.cq,a,b),25),a.cq(b));
g.Xp(a.element,"ytp-upnext-autoplay-paused")},m7=function(a){l7(a);
a.I=(0,g.aH)();a.cq();g.S(a.element,"ytp-upnext-autoplay-paused")},l7=function(a){a.A&&(a.A.dispose(),a.A=null)},gya=function(a){i7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Fa(this.element);this.B=new g.i1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Sl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Fa(this.A.va["html5-subscribe-button-container"]);this.hide()},
n7=function(a){var b=g.X(a);
b=b.A&&!b.F;g.Y.call(this,{H:"a",M:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",R:g.vF||g.cf?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.D);if(g.X(a).da){a=a.app.da;b=this.element;g.jb(a.g,b);g.nb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.Ye(this,(0,g.A)(a.F,a,b))}},o7=function(a){i7.call(this,a,"videowall-endscreen");
this.aa=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.V=!1;this.F=new g.wG(this);g.M(this,this.F);this.L=new g.Jt(g.Ba(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.yE()]});g.M(this,b);b.Fa(this.element);b.U("click",this.EM,this);this.O=new g.KW({H:"div",M:"ytp-endscreen-content"});g.M(this,this.O);this.O.Fa(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.U("YTP_NEXT")},K:[g.zE()]});g.M(this,b);b.Fa(this.element);b.U("click",this.DM,this);this.A=new j7(a);g.M(this,this.A);g.CW(this.o,this.A.element,4);this.hide()},p7=function(a){return g.DW(a.o)&&a.hq()&&!a.I},hya=function(a){return(0,g.J)(a.mg,function(a){return g.l_(a)})},iya=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.X(a.o).experiments.g("video_wall_emphasize_first")?4:2},q7=function(a){var b=a.Es();
b!=a.V&&(a.V=b,a.o.X("autonavvisibility"))},r7=function(a){g.eX.call(this,a);
g.uE({});this.o=null;this.isAvailable=!0;this.A=new g.wG(this);g.M(this,this.A);this.B=g.X(a);jya(a)?this.o=new o7(this.g):this.B.sa?this.o=new gya(this.g):this.o=new i7(this.g);g.M(this,this.o);g.CW(this.g,this.o.element,4);this.eC();this.A.P(a,"videodatachange",this.eC,this);this.A.P(a,"crn_endscreen",this.gM,this);this.A.P(a,"crx_endscreen",this.hM,this)},jya=function(a){a=g.X(a);
return a.hd&&!a.sa};g.p(i7,g.jX);i7.prototype.create=function(){this.N=!0};
i7.prototype.destroy=function(){this.N=!1};
i7.prototype.hq=function(){return!1};
i7.prototype.Es=function(){return!1};g.p(j7,g.Y);g.h=j7.prototype;g.h.Rm=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.RA=function(){g.QW(this,g.bW(this.o))};
g.h.HQ=function(){window.focus();this.Rm()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.cq=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.aH)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Ya()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.pW(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.gc(),this.Rm(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.dc(b)}),this.F=this.P(this.D,"click",this.HQ),this.G.start())}l7(this);
this.o.Cj(!1,a)};
g.h.QQ=function(a){!g.Pd(this.B.element,g.mG(a))&&g.$Z(a,this.o)&&this.select()};
g.h.UA=function(){g.qW(this.o,"autonavcancel");g.dW(this.o,!0)};
g.h.gQ=function(a){this.o.Ya();this.show();k7(this,a)};
g.h.hD=function(a){this.o.Ya();this.C&&this.C.gc().videoId==a.gc().videoId||fya(this,a)};
g.h.hQ=function(){this.o.Ya();l7(this);this.hide()};
g.h.W=function(){l7(this);this.Rm();g.Y.prototype.W.call(this)};g.p(gya,i7);g.p(n7,g.Y);n7.prototype.Sj=function(){var a=this.A.gc().videoId,b=this.A.getPlaylistId();g.U1(this.o.app,a,this.A.Xd,b,void 0,void 0)};
n7.prototype.C=function(a){g.GW(this.o,this.element);g.$Z(a,this.o,this.B,this.A.Xd||void 0)&&this.Sj()};
n7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.rG(a)||(this.Sj(),g.tG(a))}};g.p(o7,i7);g.h=o7.prototype;g.h.create=function(){i7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=hya(a),this.D=a);this.vh();this.F.P(this.o,"appresize",this.vh);this.F.P(this.o,"videodatachange",this.FM);this.F.P(this.o,"autonavchange",this.Rz);this.F.P(this.o,"autonavcancel",this.CM);this.F.P(this.element,"transitionend",this.WR)};
g.h.destroy=function(){g.yG(this.F);g.$e(this.B);this.B=[];this.C=null;i7.prototype.destroy.call(this);g.Xp(this.element,"ytp-show-tiles");this.L.stop()};
g.h.hq=function(){return 1!=this.D.autonavState};
g.h.show=function(){i7.prototype.show.call(this);g.Xp(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.Kt(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.dW(this.o,!1);var a=p7(this);g.DW(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.pW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.hq()?"enabled":"disabled"});a?(q7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.co()?this.A.select(!0):k7(this.A):3==this.D.autonavState&&
m7(this.A)):(g.dW(this.o,!0),q7(this))};
g.h.hide=function(){i7.prototype.hide.call(this);m7(this.A);q7(this)};
g.h.WR=function(a){g.mG(a)==this.element&&this.vh()};
g.h.vh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Hh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=l*m,q=iya(this,0,k),r=iya(this,1,k);n+=Math.pow(q,2)-m;n+=Math.pow(r,2)-m;for(n-=m;0<n&&(d<f||e<k);){var w=d/2,z=e/2,B=d<=f-2&&n>=z*m,C=e<=k-2&&n>=w*m;if((w+1)/z*c/b>b/(w/(z+1)*c)&&C)n-=w*m,e+=2;else if(B)n-=z*m,d+=2;else if(C)n-=w*m,e+=2;else break}c=!1;f=2+q;n>=3*m&&
6>=l*m-n&&(e>=f||d>=f)&&2>=r&&(c=!0);m=96*d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.Yc(a.width/m||1,1,1.21);n*=g.Yc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Gh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});fya(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",p7(this));q7(this);m+=4;n+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(z=2<r&&1<=b&&!f?b+1:b,B=0,c&&k>=d-2&&w>=e-2?B=1:0==
w%2&&0==k%2&&(w<q&&k<q?0==w&&0==k&&(B=q):2<r&&w>=e-r&&k>=d-r?w==e-r&&k==d-r&&(f=!0,z=1,B=r):B=2),z=g.Zc(z+this.G,l),0!=B){C=this.B[b];C||(C=new n7(this.o),this.B[b]=C,a.appendChild(C.element));var N=Math.floor(n*w/e),da=Math.floor(m*k/d),Ga=Math.floor(n*(w+B)/e)-N-4,Da=Math.floor(m*(k+B)/d)-da-4;g.vh(C.element,da,N);g.Gh(C.element,Da,Ga);g.oh(C.element,"transitionDelay",(w+k)/20+"s");g.T(C.element,"ytp-videowall-still-mini",1==B);g.T(C.element,"ytp-videowall-still-large",2<B);B=C;z=this.C[z];B.A=
z;eya(B,z,g.X(B.o),g.Vp(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");C=z.Xd;z=B.o;g.X(z).da&&(z=z.app.da,B=B.element,C=C&&C.itct,N=B.getAttribute("data-visual-id"),g.jb(z.g,B),g.EW(z,"onLogServerVeCreated",{id:N,tracking_params:C}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Hd(e.element),g.Ze(e);this.B.length=b}};
g.h.FM=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=hya(a),this.D=a,this.vh())};
g.h.DM=function(){this.G+=this.B.length;this.vh()};
g.h.EM=function(){this.G-=this.B.length;this.vh()};
g.h.uK=function(){return!!this.A.A};
g.h.Rz=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,l7(this.A),this.g&&this.vh()):(this.J=!0,this.g&&p7(this)&&(2==a?k7(this.A):3==a&&m7(this.A)))};
g.h.CM=function(a){if(a){for(a=0;a<this.B.length;a++)g.HW(this.aa,this.B[a].element,!0);this.Rz(1)}else this.I=null,this.J=!1;this.vh()};
g.h.Es=function(){return this.g&&p7(this)};g.p(r7,g.eX);g.h=r7.prototype;g.h.Oz=function(){var a=this.g.ga(),b=!jya(this.g)||!(!a.mg||!a.mg.length);a=g.CQ(a,"ypc_module");var c=g.V1(this.g.app);return(b||!1)&&!a&&!c};
g.h.Nz=function(){return this.o.Es()};
g.h.rK=function(){return this.Nz()?this.o.uK():!1};
g.h.W=function(){g.yW(this.g,"endscreen");g.eX.prototype.W.call(this)};
g.h.load=function(){g.eX.prototype.load.call(this);this.o.show();g.X(this.g).sa&&.01>Math.random()&&g.pW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.eX.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.gM=function(a){this.Oz()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.hM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.eC=function(){g.yW(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0);a=new g.XJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.XJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.vW(this.g,[a,b])};g.qX("endscreen",r7);})(_yt_player);
